Fix Destroy compile time error
Project refused to build post upgrade to 0.30.0.

Error:
error CS0103: The name `Destroy' does not exist in the current context